# reference: https://wiki.osdev.org/X86-64_Instruction_Encoding#LOCK_prefix
lock_opcodes = ['ADC',
                'ADD',
                'AND',
                'BTC',
                'BTR',
                'BTS',
                'CMPXCHG',
                'CMPXCHG8B',
                'CMPXCHG16B',
                'DEC',
                'INC',
                'NEG',
                'NOT',
                'OR',
                'SBB',
                'SUB',
                'XADD',
                'XCHG',
                'XOR']
